export default function Home() {
  const meals = [
    { day: 'Sunday', meal: 'Chicken thighs, smashed potatoes, green beans', leftovers: true },
    { day: 'Monday', meal: 'Salmon, cous cous, roasted broccoli', leftovers: false },
    { day: 'Tuesday', meal: 'Honey garlic pork tenderloin, rice, snap peas', leftovers: true },
    { day: 'Wednesday', meal: 'Pork egg roll bowls', leftovers: true },
    { day: 'Thursday', meal: 'Lemon garlic chicken, green beans', leftovers: true },
    { day: 'Friday', meal: 'Sausage and kale with crusty bread', leftovers: false },
  ];

  const staples = [
    { item: 'Bananas', qty: '1 bunch' },
    { item: 'Hummus (garlic/pine nut)', qty: '1 container' },
    { item: 'Lactaid 2% milk', qty: '1 gallon' },
    { item: 'Fage yogurt', qty: '8 cups' },
    { item: 'Stok bold iced coffee', qty: '2 bottles' },
    { item: 'Water (gallon jugs)', qty: '3' },
    { item: 'Water (2.5gal fridge)', qty: '2' },
  ];

  const household = [
    { item: 'Paper towels', needed: true },
  ];

  const dadsStore = [
    { item: 'Salmon fillet', qty: '~1.5 lbs' },
    { item: 'Apples', qty: '6-8' },
  ];

  return (
    <div style={{ fontFamily: 'system-ui, sans-serif', maxWidth: '800px', margin: '0 auto', padding: '20px' }}>
      <header style={{ borderBottom: '2px solid #333', paddingBottom: '10px', marginBottom: '20px' }}>
        <h1>🍽️ Weekly Meal Plan</h1>
        <p style={{ color: '#666' }}>Week of Feb 23 - Mar 1 • Brian & Gianna</p>
      </header>

      <section style={{ marginBottom: '30px' }}>
        <h2>Dinners</h2>
        <div style={{ display: 'grid', gap: '10px' }}>
          {meals.map((m, i) => (
            <div key={i} style={{ 
              padding: '15px', 
              background: m.leftovers ? '#e8f5e9' : '#f5f5f5',
              borderRadius: '8px',
              borderLeft: m.leftovers ? '4px solid #4caf50' : '4px solid #ccc'
            }}>
              <strong>{m.day}</strong>
              <p style={{ margin: '5px 0' }}>{m.meal}</p>
              {m.leftovers && <span style={{ fontSize: '12px', color: '#4caf50' }}>🍱 Leftovers for lunch</span>}
            </div>
          ))}
        </div>
      </section>

      <section style={{ marginBottom: '30px' }}>
        <h2>🛒 Grocery List</h2>
        <h3>Proteins (organic)</h3>
        <ul>
          <li>Chicken thighs, bone-in — 3 lbs</li>
          <li>Pork tenderloin — 2 lbs</li>
          <li>Ground pork — 1.5 lbs</li>
          <li>Chicken breasts — 2.5 lbs</li>
          <li>Italian sausage — 1 lb</li>
        </ul>

        <h3>Produce</h3>
        <ul>
          <li>Mini potatoes — 3 lbs</li>
          <li>Green beans — 2 lbs</li>
          <li>Broccoli — 1 head</li>
          <li>Broccoli slaw — 1 bag</li>
          <li>Snap peas — 1 lb</li>
          <li>Kale — 1 bunch</li>
          <li>Yellow onions — 2</li>
          <li>Garlic — 1 head</li>
          <li>Fresh ginger</li>
        </ul>

        <h3>Pantry</h3>
        <ul>
          <li>Far East cous cous (garlic/pine nut/chicken)</li>
          <li>White rice</li>
          <li>Wonton salad toppers</li>
        </ul>
      </section>

      <section style={{ marginBottom: '30px', background: '#fff3e0', padding: '15px', borderRadius: '8px' }}>
        <h2>📦 Weekly Staples</h2>
        <ul>
          {staples.map((s, i) => (
            <li key={i}>{s.item} — {s.qty}</li>
          ))}
        </ul>
      </section>

      {household.some(h => h.needed) && (
        <section style={{ marginBottom: '30px', background: '#ffebee', padding: '15px', borderRadius: '8px' }}>
          <h2>🏠 Household</h2>
          <ul>
            {household.filter(h => h.needed).map((h, i) => (
              <li key={i}>{h.item} — <strong>NEEDED THIS WEEK</strong></li>
            ))}
          </ul>
        </section>
      )}

      <section style={{ marginBottom: '30px', background: '#e3f2fd', padding: '15px', borderRadius: '8px' }}>
        <h2>🏪 Dad's Store (Market of Lafayette Hill)</h2>
        <ul>
          {dadsStore.map((d, i) => (
            <li key={i}>{d.item} — {d.qty}</li>
          ))}
        </ul>
      </section>

      <footer style={{ borderTop: '1px solid #ccc', paddingTop: '20px', color: '#666', fontSize: '14px' }}>
        <p>💰 Estimated cost: ~$85-95 (Giant) + ~$25-35 (Dad's Store)</p>
        <p>🚀 Generated by Roci • Saturday 8:30 AM</p>
      </footer>
    </div>
  );
}
