import { useState, useEffect } from 'react';
import Nav from '../components/Nav';

export default function Home() {
  const [weeklyPlan, setWeeklyPlan] = useState([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const savedPlan = localStorage.getItem('weeklyPlan');
    if (savedPlan) {
      setWeeklyPlan(JSON.parse(savedPlan));
    }
    setLoading(false);
  }, []);

  const leftoversCount = weeklyPlan.filter(d => d.meal?.hasLeftovers).length;

  if (loading) {
    return (
      <div style={{ fontFamily: 'system-ui, sans-serif', maxWidth: '900px', margin: '0 auto', padding: '20px' }}>
        <p>Loading your meal plan...</p>
      </div>
    );
  }

  if (weeklyPlan.length === 0) {
    return (
      <div style={{ fontFamily: 'system-ui, sans-serif', maxWidth: '900px', margin: '0 auto', padding: '20px' }}>
        <header style={{ borderBottom: '2px solid #333', paddingBottom: '10px', marginBottom: '20px' }}>
          <h1>🍽️ Weekly Meal Plan</h1>
          <p style={{ color: '#666' }}>Brian & Gianna</p>
        </header>

        <Nav />

        <div style={{ 
          background: '#fff3e0', 
          padding: '30px', 
          borderRadius: '8px', 
          textAlign: 'center',
          marginTop: '40px'
        }}>
          <h2>No meal plan yet!</h2>
          <p style={{ marginBottom: '20px' }}>
            Your meal plan will appear here after Roci sends you the Saturday proposal.
          </p>
          <p style={{ color: '#666' }}>
            Every Saturday at 8:30 AM, you'll get a message on Telegram with this week's meal plan.
          </p>
        </div>
      </div>
    );
  }

  return (
    <div style={{ fontFamily: 'system-ui, sans-serif', maxWidth: '900px', margin: '0 auto', padding: '20px' }}>
      <header style={{ borderBottom: '2px solid #333', paddingBottom: '10px', marginBottom: '20px' }}>
        <h1>🍽️ Weekly Meal Plan</h1>
        <p style={{ color: '#666' }}>Week of {new Date().toLocaleDateString()} • Brian & Gianna</p>
      </header>

      <Nav />

      <div style={{ 
        background: '#e3f2fd', 
        padding: '15px', 
        borderRadius: '8px', 
        marginBottom: '20px',
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center'
      }}>
        <div>
          <strong>📊 This Week's Plan</strong>
          <p style={{ margin: '5px 0 0 0' }}>
            {weeklyPlan.length} dinners • {leftoversCount} with leftovers
          </p>
        </div>
        <div style={{ fontSize: '24px' }}>
          {leftoversCount >= 4 ? '✅' : '⚠️'}
        </div>
      </div>

      <div style={{ display: 'grid', gap: '10px' }}>
        {weeklyPlan.map((day) => (
          <div key={day.day} style={{ 
            padding: '15px', 
            background: day.meal?.hasLeftovers ? '#e8f5e9' : '#f5f5f5',
            borderRadius: '8px',
            borderLeft: day.meal?.hasLeftovers ? '4px solid #4caf50' : '4px solid #ccc'
          }}>
            <strong>{day.day}</strong>
            <p style={{ margin: '5px 0' }}>{day.meal?.name || 'No meal selected'}</p>
            {day.meal?.hasLeftovers && (
              <span style={{ fontSize: '12px', color: '#4caf50' }}>🍱 Leftovers for lunch</span>
            )}
          </div>
        ))}
      </div>

      <div style={{ 
        background: '#e8f5e9', 
        padding: '20px', 
        borderRadius: '8px', 
        marginTop: '30px',
        textAlign: 'center'
      }}>
        <p style={{ margin: '0 0 10px 0', fontSize: '16px' }}>
          Want to change this week's plan?
        </p>
        <p style={{ margin: '0 0 15px 0', color: '#666' }}>
          Message Roci on Telegram to request swaps or adjustments.
        </p>
        <a 
          href="/grocery" 
          style={{
            display: 'inline-block',
            padding: '12px 24px',
            background: '#4caf50',
            color: 'white',
            textDecoration: 'none',
            borderRadius: '4px',
            fontWeight: 'bold'
          }}
        >
          View Grocery List →
        </a>
      </div>

      <footer style={{ borderTop: '1px solid #ccc', paddingTop: '20px', marginTop: '30px', color: '#666', fontSize: '14px' }}>
        <p>🚀 Generated by Roci • Plan updates via Telegram</p>
      </footer>
    </div>
  );
}
